apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cuservice
spec:
  #serviceName: "nginxstor"
  replicas: 1
  template:
    metadata:
      labels:
        app: <container name>
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      # soft antiaffinity for optimize placement
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - <container name>
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-myservice
        image: busybox:latest
        # use service port not container port
        command: ['sh', '-c', 'until nc -v -z -w 1 <<before module-service name>> <<before module-service port>>; do echo waiting for myservice; sleep 2; done;']
      - name: sleepforit
        image: busybox:latest
        command: ['sh', '-c', 'sleep 1m']
      containers:
      - name: <container name>
        image: <image name>
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: /etc/localtime
          name: hosttime
      volumes:
       - name: hosttime
         hostPath:
           path: /etc/localtime
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
